export const RESUME_LIST_REQUEST = "RESUME_LIST_REQUEST";
export const RESUME_LIST_SUCCESS = "RESUME_LIST_SUCCESS";
export const RESUME_LIST_FAIL = "RESUME_LIST_FAIL";

export const NOTES_CREATE_REQUEST = "NOTES_CREATE_REQUEST";
export const NOTES_CREATE_SUCCESS = "NOTES_CREATE_SUCCESS";
export const NOTES_CREATE_FAIL = "NOTES_CREATE_FAIL";

export const NOTES_UPDATE_REQUEST = "NOTES_UPDATE_REQUEST";
export const NOTES_UPDATE_SUCCESS = "NOTES_UPDATE_SUCCESS";
export const NOTES_UPDATE_FAIL = "NOTES_UPDATE_FAIL";

export const NOTES_DELETE_REQUEST = "NOTES_DELETE_REQUEST";
export const NOTES_DELETE_SUCCESS = "NOTES_DELETE_SUCCESS";
export const NOTES_DELETE_FAIL = "NOTES_DELETE_FAIL";

export const NOTES_SHARE_REQUEST = "NOTES_SHARE_REQUEST";
export const NOTES_SHARE_SUCCESS = "NOTES_SHARE_SUCCESS";
export const NOTES_SHARE_FAIL = "NOTES_SHARE_FAIL";

export const SHARED_NOTES_LIST_REQUEST = "SHARED_NOTES_LIST_REQUEST";
export const SHARED_NOTES_LIST_SUCCESS = "SHARED_NOTES_LIST_SUCCESS";
export const SHARED_NOTES_LIST_FAIL = "SHARED_NOTES_LIST_FAIL";

export const RESUME_SAVE_REQUEST = "RESUME_SAVE_REQUEST";
export const RESUME_SAVE_SUCCESS = "RESUME_SAVE_SUCCESS";
export const RESUME_SAVE_FAIL = "RESUME_SAVE_FAIL";
