export const RESUME_LIST_REQUEST = "RESUME_LIST_REQUEST";
export const RESUME_LIST_SUCCESS = "RESUME_LIST_SUCCESS";
export const RESUME_LIST_FAIL = "RESUME_LIST_FAIL";

export const RESUME_SAVE_REQUEST = "RESUME_SAVE_REQUEST";
export const RESUME_SAVE_SUCCESS = "RESUME_SAVE_SUCCESS";
export const RESUME_SAVE_FAIL = "RESUME_SAVE_FAIL";
